### ISSUE TITLE
Reproduce the results of the paper

### ISSUE THREAD

**Issue by biubug6** [YueLiao/gen-vlkt#10]
Hello, thank you for your code;  But I can't reproduce the result of  GEN-VLKTs.
I execute the script[https://github.com/YueLiao/gen-vlkt/blob/master/configs/hico_s.sh](url) and get best result in hico_det below：
"mAP full: 0.33093688795372056 mAP rare: 0.2844252297058811  mAP non-rare: 0.34482998067710124  mean max recall: 0.6672380371879575".
ps: 8 Tesla V100 GPUs.
paper result:
mAP full: 0.3375

**Comment by YueLiao** [comment]
Hi, thanks for your interests in our work. You may evaluate the result with the HICO-det official evaluation (reported in the paper), which maybe a little different from our provided python version. Let me know this result for latter debug.

**Comment by YueLiao** [comment]
Long time no response. Feel free to reopen this issue if any problems.

**Comment by BingliangLi** [comment]
> Hi, thanks for your interests in our work. You may evaluate the result with the HICO-det official evaluation (reported in the paper), which maybe a little different from our provided python version. Let me know this result for latter debug.

HI, could you please provide me the link to the official evaluation you reffered? Is it this one: https://github.com/fredzzhang/hicodet ?
