### ISSUE TITLE
Reproduce the results of the paper

### ISSUE THREAD

**Issue by AssiduousMan** [YueLiao/gen-vlkt#11]
Hello, thank you for your code; But I can't reproduce the result of GEN-VLKTs.
I execute the script[https://github.com/YueLiao/gen-vlkt/blob/master/configs/hico_s.sh](https://github.com/YueLiao/gen-vlkt/issues/url) and get best result in hico_det below：
"mAP full: 0.30144832960135726 mAP rare: 0.2543793789379969  mAP non-rare: 0.31550788629301035  mean max recall: 0.6205516668727018"
ps: 1 3090 GPU.
paper result:
mAP full: 0.3375

**Comment by YueLiao** [comment]
Hi, could you provide the batch size and learning rate? Our config is based on 4 or 8 GPUs.

**Comment by AssiduousMan** [comment]
> 

envirmoments are as follows:
python=3.8
certifi           2022.6.15
clip              1.0         /home/wyx/program/gen-vlkt/CLIP
cycler            0.11.0
Cython            0.29.32
fonttools         4.37.1
ftfy              6.1.1
kiwisolver        1.4.4
matplotlib        3.5.3
mkl-fft           1.3.0
mkl-random        1.1.1
mkl-service       2.3.0
numpy             1.23.3
opencv-python     4.6.0.66
packaging         21.3
Pillow            9.2.0
pip               22.1.2
pycocotools       2.0.4
pyparsing         3.0.9
python-dateutil   2.8.2
regex             2022.9.13
scipy             1.3.1
setuptools        63.4.1
six               1.16.0
torch             1.7.1+cu110
torchvision       0.8.2+cu110
tqdm              4.64.1
typing_extensions 4.3.0
wcwidth           0.2.5
wheel             0.37.1

learning rate: 1e-4
batch_size: 2
thank you

**Comment by AssiduousMan** [comment]
> Hi, could you provide the batch size and learning rate? Our config is based on 4 or 8 GPUs.

in hico_s.sh, I set the nproc_per_node=1, because i only have one gpu that 3090
learning rate: 1e-4
batch_size: 2

**Comment by YueLiao** [comment]
The problems may lie in the small batch size. You may try with large batch size. 30 is a very unreasonable result.

**Comment by AssiduousMan** [comment]
> The problems may lie in the small batch size. You may try with large batch size. 30 is a very unreasonable result. The mAP should be in [33-33.5] by the Python evaluation script and 33.75 ± 0.2 by the official Matlab evaluation script.

ok, i try to it again by using your advice. thank you. if i have a latest results，i will reply here. thank you again.
