### ISSUE TITLE
how to initialize the instance decoder query

### ISSUE THREAD

**Issue by jojolee123** [YueLiao/gen-vlkt#12]
Does the paper initialize human query and object query to different values,then self-attention together?
I think instance decoder focus on parts feature, so human query and object query should go to self-attention separately as it in [Reference Paper 5], i cannot find description about this in paper.
waiting for your reply,Thank you!

**Comment by YueLiao** [comment]
Hi, the human and object queries are both with random initialization and add the same position embedding in the same position.
