### ISSUE TITLE
Question regarding zero-shot inference 

### ISSUE THREAD

**Issue by ASMIftekhar** [YueLiao/gen-vlkt#14]
Hello, Thanks for your nice work.

I have a question regarding zero-shot inference. It seems that during inference you directly utilize frozen clip embeddings. However, during training you trained a 'dummy' interaction classifier on seen classes, this classifier does not have any effect in the inference phase. Do I understand this correctly?

**Comment by YueLiao** [comment]
Hi, during the training process for the zero-shot setting, the interaction classifier is also frozen and initialized with clip embeddings.
