### ISSUE TITLE
How to obtain the Know object result of the HICO dataset

### ISSUE THREAD

**Issue by xiaowuzuida** [YueLiao/gen-vlkt#18]
hello, i see the results of the code is about default(include full, rare, and non-rare) in HICO dataset, but i want to get the Know object result(include full, rare, and non-rare) in HICO dataset. So, how should i do, could you tell me, thanks you very much!

**Comment by YueLiao** [comment]
Hi, the Know Object results can be obtained by the official HICO-DET evaluation, and the official evaluation pipeline has been provided in the README.MD.

**Comment by hxqstree** [comment]
hi,i see the "covert_annot_for_official_eval.py" needs json format input, may i ask how this json file is obtained

**Comment by YueLiao** [comment]
> hi,i see the "covert_annot_for_official_eval.py" needs json format input, may i ask how this json file is obtained

Hi, the 'results.json' file was generated when you ran the 'Evaluation' steps. Details can be found in the hico_eval.py or hico_eval_triplet.py.
