### ISSUE TITLE
How to reproduce the 'base-verb' experiments

### ISSUE THREAD

**Issue by HeejiWon** [YueLiao/gen-vlkt#19]
Hi, thank you for your nice work:) 
I'm interested in the ablation study about 'base-verb' setting. 
Can I get a command or code for the 'base-verb' experiment to reproduce the ablation study reported in your paper?
Also, I'm curious about how did you make text embedding for the verb classifier.
Thanks!

**Comment by YueLiao** [comment]
Sorry for the latter reply; due to some significant deadlines~
We will update the repo with this setting soon (today or tomorrow).

**Comment by YueLiao** [comment]
Taking #21 as the reference.
