### ISSUE TITLE
Questions about Text Embedding for Classifier Initialization.

### ISSUE THREAD

**Issue by SherlockHolmes221** [YueLiao/gen-vlkt#2]
How do you convert the 512-d CLIP vectors into 256-d to init the classifier? Thanks

**Comment by YueLiao** [comment]
We adopt a linear layer to transform the output visual features of the decoder into 512-d.

**Comment by SherlockHolmes221** [comment]
The lr of the  linear layer and the classifier are both 1e-5?

**Comment by YueLiao** [comment]
Only the classifier.
