### ISSUE TITLE
Warning in evaluation code

### ISSUE THREAD

**Issue by jonghakim35** [YueLiao/gen-vlkt#20]
Hi, thanks for sharing your great work.

While training the model, warnings below occur.

![image](https://user-images.githubusercontent.com/34956703/222753618-6836dd00-6060-44a1-a27c-7fefc05d6af8.png)

It seems that in early training stage, such error occurs quite often. Is there a reason why is the warning being printed?

Thanks.

**Comment by YueLiao** [comment]
Hi, since the model fails to detect some HOI triplets in the early training stage, it is a normal phenomenon.
