### ISSUE TITLE
Would you release the baseline config of Table.3 Zero-Shot HOI Detection?

### ISSUE THREAD

**Issue by nanfangAlan** [YueLiao/gen-vlkt#23]
Hello. Would you release the baseline config of Table.3 Zero-Shot HOI Detection? Did baseline classifiers initiate without the text embeddings? thanks.

**Comment by YueLiao** [comment]
The baseline was implemented with GEN (w/o VLKT), whose classifiers (GEN) didn't initiate with text embeddings.

**Comment by nanfangAlan** [comment]
Thanks for your replying. Now I'm confused about how can baseline get such a high performance on Unseen-Verb (13.52), which is even better than RF-UC(12.52)

**Comment by YueLiao** [comment]
The mAP is evaluated across all unseen HOI triplets, and the scores of final HOI triplet predictions are made up of the 'HOI triplet categories scores' and the corresponding 'object categories scores'. Therefore, the object confidence scores are able to contribute a relatively high confidence for the 'unseen verb' HOI triplets, if the object was detected in the image.

**Comment by nanfangAlan** [comment]
Thanks, I got it. This may also be the reason why UO has the worst performance.
