### ISSUE TITLE
Question about NMS

### ISSUE THREAD

**Issue by chohoseong** [YueLiao/gen-vlkt#25]
Hi, thank you for your nice work.

I have question about the nms filtering.

Have other works also applied nms filtering during evaluation?
As far as I know, QPIC doesn't use nms filtering. 

I'm curious if this is the correct basis for a fair comparison.

**Comment by YueLiao** [comment]
Such NMS operation is proposed in our previous work [CDN](https://proceedings.neurips.cc/paper/2021/file/8f1d43620bc6bb580df6e80b0dc05c48-Paper.pdf), which also provided an ablation study about NMS. It shows that NMS only improves the mAP by 0.4%.
