### ISSUE TITLE
【BUG】in the evaluation API: triplet in self.rare_triplets

### ISSUE THREAD

**Issue by Dawn-LX** [YueLiao/gen-vlkt#26]
https://github.com/YueLiao/gen-vlkt/blob/fae86113a0dea2622fd137d00948e16453a622f7/datasets/hico_eval_triplet.py#L150C48-L150C48

here, the `triplet in self.rare_triplets` should use 3-tuple, not the idx (0~600) of hoi

**Comment by YueLiao** [comment]
Thx for pointing out this. We will fix this bug, but this bug will not affect the final mAP.

**Comment by YueLiao** [comment]
Thx for pointing out this. We will fix this bug, but this bug will not affect the final mAP.

**Comment by Dawn-LX** [comment]
> Thx for pointing out this. We will fix this bug, but this bug will not affect the final mAP.

Thank you for your quick reply.
