### ISSUE TITLE
why not adopt the UA splits in ConsNet on HICO-DET?

### ISSUE THREAD

**Issue by jxgu1016** [YueLiao/gen-vlkt#3]
Why introduce the new split UV, which as far as I can tell, is similar to the UA splits in ConsNet？

**Comment by YueLiao** [comment]
Hi, they are very similar, but we didn't notice the ConsNet in the submission stage~

**Comment by jxgu1016** [comment]
Thanks for your quick reply, and will you update the result on the UA splits in ConsNet?

**Comment by YueLiao** [comment]
Yes, but not recently.

**Comment by jxgu1016** [comment]
OK, please keep me updated.

**Comment by jxgu1016** [comment]
I run the UA experiments and the best test results are ```"test_mAP": 0.26278824470223205, "test_mAP unseen": 0.2085273572052837, "test_mAP seen": 0.287214266430911```.

The UA splits are:
```
"unseen_action" : [2, 10, 14, 20, 27, 33, 36, 42, 46, 57, 68, 81, 82, 86, 90, 92, 101, 103,
                       109, 111, 116, 120, 121, 122, 123, 136, 137, 138, 140, 141, 149, 152, 155,
                       160, 161, 170, 172, 174, 180, 188, 205, 208, 215, 222, 225, 236, 247, 260,
                       265, 271, 273, 279, 283, 288, 295, 300, 301, 306, 310, 311, 315, 318, 319,
                       337, 344, 352, 356, 363, 369, 373, 374, 419, 425, 427, 438, 453, 458, 461,
                       464, 468, 471, 475, 480, 486, 489, 490, 496, 504, 506, 513, 516, 524, 528,
                       533, 542, 555, 565, 576, 590, 597]
```
following [ConsNet](https://github.com/yeliudev/ConsNet/blob/e0d7c1a455ec126498ee41bd3fd918d82569acc8/consnet/api/static.py#L165).

Please help me confirm this results.

**Comment by YueLiao** [comment]
It looks like no problem~ We are busy with some deadlines, thus no spare time to verify it recently.
